apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-simple2
  labels:
    app: springboot-simple2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-simple2
  template:
    metadata:
      labels:
        app: springboot-simple2
    spec:
      containers:
      - name: springboot-simple
        image: registry.gitlab.com/dariuscooper/springboot-simple:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: myvol
          mountPath: /data
      imagePullSecrets:
      - name: reg-gitlab-darius  
      volumes:
      - name: myvol
        persistentVolumeClaim:
           claimName: myapp-nfs      
        
        