apiVersion: v1
kind: Service
metadata:
  labels:
    app: inte-inte
  name: inte-inte
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 32081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: inte-inte
  sessionAffinity: None
  type: NodePort
