apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-simple
  name: springboot-simple
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 32081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-simple
  sessionAffinity: None
  type: NodePort
